/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORM;




import Code.ChiTietHoaDon;
import Code.ChiTietHoaDonModify;
import Code.HoaDon;
import Code.HoaDonModify;
import Code.KhachHang;
import Code.KhachHangModify;
import Code.MaKM;
import Code.MaKmModify;
import Code.SanPham;
import Code.SanPhamModify;
import Code.TaoCode;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class CHITIETHOADONFORM extends javax.swing.JFrame {
    
    DefaultTableModel tableModel;
    int selectedIndex=-1;
    String maKH;
    String maKM;
    String ghiChu;
    String ngayBan;
    public int giamGia=0;
    boolean diemtichluy=false;
    List<ChiTietHoaDon> cthdList =new ArrayList<>();
    /**
     * Creates new form CHITIETHOADONFORM
     */
     public CHITIETHOADONFORM() {
        initComponents(); 
        tableModel=(DefaultTableModel) tblCthd.getModel();
        
       this.setLocation(200, 200);
     
    }  
    public CHITIETHOADONFORM(String maHD,String Chucvu,String makh
        ,String ngayban,String ghichu,String tonghoadon) {
        initComponents();
        this.setLocation(200, 200);
        txtMahd.setText(maHD);
        txtChucvu.setText(Chucvu);
        txtTongcong.setText(tonghoadon);
        txtMakh.setText(makh);
        txtNgayban.setText(ngayban);
        txtTenkh.setText(KhachHangModify.findByID(makh).getTenKH());
        maKH=makh;
        ghiChu=ghichu;
        ngayBan=ngayban;
        txtDiemtichluy.setText(""+KhachHangModify.findByID(makh).getDiemTichLuy());
        tableModel=(DefaultTableModel) tblCthd.getModel();
    
    }

    public void showCTHD(){
        tableModel.setRowCount(0);
        cthdList.forEach(cthd -> {
            tableModel.addRow(new Object[] {cthd.getMaHD(),
                cthd.getMaCTHD(),cthd.getMaSP(),
                SanPhamModify.findByID(cthd.getMaSP()).getTenSP(),
                cthd.getSoLuong(),
                SanPhamModify.findByID(cthd.getMaSP()).getGiaXuat(),
                cthd.getThanhTien()
            });
           
        });
    }
    public void tinhTienCTHD(){
        int tongcthd=0;    
        for(int i=0;i<cthdList.size();i++){
            tongcthd+=cthdList.get(i).getThanhTien();
        }
        txtTongcong.setText(""+tongcthd);    
    }
    
 
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCthd = new javax.swing.JTable();
        btnThanhtoan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtChucvu = new javax.swing.JLabel();
        btnSanpham = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtMahd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDiemtichluy = new javax.swing.JTextField();
        checkDiemtichluy = new javax.swing.JCheckBox();
        txtTongcong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTonghoadon = new javax.swing.JTextField();
        btnMakm = new javax.swing.JButton();
        txtMakm = new javax.swing.JTextField();
        btnHuy = new javax.swing.JButton();
        btnThanhtien = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMakh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNgayban = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTenkh = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("CHI TIẾT HÓA ĐƠN");

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Delete(1).png"))); // NOI18N
        btnDelete.setText("XÓA");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblCthd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MACTHD", "MASP", "TENSP", "SOLUONG", "GIABAN", "THANHTIEN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCthd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCthdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCthd);

        btnThanhtoan.setBackground(new java.awt.Color(204, 204, 255));
        btnThanhtoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Apply(1).png"))); // NOI18N
        btnThanhtoan.setText("THANH TOAN");
        btnThanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhtoanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Chức vụ :");

        txtChucvu.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txtChucvu.setText("jLabel3");

        btnSanpham.setText("THEM SAN PHAM");
        btnSanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanphamActionPerformed(evt);
            }
        });

        jLabel7.setText("MÃ HD");

        txtMahd.setEditable(false);
        txtMahd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMahdActionPerformed(evt);
            }
        });

        jLabel6.setText("MA KHUYEN MAI");

        jLabel8.setText("Diem tich luy");

        txtDiemtichluy.setEditable(false);
        txtDiemtichluy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemtichluyActionPerformed(evt);
            }
        });

        checkDiemtichluy.setText("      SU DUNG");

        txtTongcong.setEditable(false);
        txtTongcong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongcongActionPerformed(evt);
            }
        });

        jLabel9.setText("TONG CONG:");

        txtTonghoadon.setEditable(false);

        btnMakm.setText("MA KHUYEN MAI");
        btnMakm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakmActionPerformed(evt);
            }
        });

        txtMakm.setEditable(false);

        btnHuy.setText("HUY HOA DON");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnThanhtien.setText("Thanh tien");
        btnThanhtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhtienActionPerformed(evt);
            }
        });

        jLabel10.setText("SAN PHAM DA CHON");

        jLabel2.setText("MA KH");

        txtMakh.setEditable(false);

        jLabel3.setText("Ngay ban");

        txtNgayban.setEditable(false);

        jLabel5.setText("TEN KH");

        txtTenkh.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel3))
                                            .addGap(59, 59, 59)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtMahd)
                                                .addComponent(txtNgayban, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                                            .addGap(48, 48, 48)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel5)))
                                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnThanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(8, 8, 8))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(196, 196, 196)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(43, 43, 43)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtMakh)
                                                .addComponent(txtTenkh, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btnSanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(81, 81, 81)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtTonghoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtTongcong, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(txtMakm, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(45, 45, 45)
                                                        .addComponent(btnMakm, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(txtDiemtichluy, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(45, 45, 45)
                                                        .addComponent(checkDiemtichluy, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(btnThanhtoan)))))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 35, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtChucvu)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMahd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSanpham)
                    .addComponent(jLabel2)
                    .addComponent(txtMakh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(jLabel3)
                    .addComponent(txtNgayban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtTenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTongcong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDiemtichluy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkDiemtichluy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMakm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMakm, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTonghoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThanhtien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThanhtoan)
                    .addComponent(btnHuy))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
//        // TODO add your handling code here:      
        if(selectedIndex>=0){
            cthdList.remove(selectedIndex);
        }
        JOptionPane.showMessageDialog(rootPane, "XÓA THÀNH CÔNG !");
        showCTHD();
        tinhTienCTHD(cthdList);    
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnThanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhtoanActionPerformed
        // TODO add your handling code here:
        if(txtTonghoadon.getText().length()>0){
        boolean isOK=false;
        int tonghd=Integer.parseInt(txtTonghoadon.getText());
        HoaDon hd=new HoaDon(txtMahd.getText(),maKH,ngayBan,tonghd,ghiChu);
        HoaDonModify.insert(hd);

        for(int i=0;i<cthdList.size();i++){
            ChiTietHoaDonModify.insert(cthdList.get(i));
            }
        if(checkDiemtichluy.isSelected()){
            KhachHang kh=KhachHangModify.findByID(maKH);
            KhachHang kh_update=new KhachHang(kh.getMaKH(),kh.getTenKH(),kh.getDiaChi(),
            kh.getSdt(),0);
            KhachHangModify.update(kh_update);
        }
        //update so luong san pham:
        
        for(int i=0;i<cthdList.size();i++){
               SanPham sp=SanPhamModify.findByID(cthdList.get(i).getMaSP());
               int nsoLuong=sp.getSoLuong()-cthdList.get(i).getSoLuong();
               SanPham nsp=new SanPham(sp.getMaSP(),sp.getTenSP(),
                       sp.getGiaNhap(),sp.getGiaXuat(),nsoLuong,sp.getDonVi(),
                       sp.getMaLoaiSP(),sp.getMaNCC());
               SanPhamModify.update(nsp);

                 
        }
        //update diem dich luy sau khi thanh toan:
            KhachHang kh=KhachHangModify.findByID(maKH);
            int ndiemtichluy=kh.getDiemTichLuy()+(tonghd/100);
 
            KhachHang kh_update=new KhachHang(kh.getMaKH(),kh.getTenKH(),kh.getDiaChi(),
            kh.getSdt(),ndiemtichluy);
            KhachHangModify.update(kh_update);
        JOptionPane.showMessageDialog(rootPane, "LƯU THÀNH CÔNG !");
        this.dispose();
        new PHIEUHOADONFORM(txtMahd.getText(),txtChucvu.getText(),txtTongcong.getText(),
            txtMakh.getText(),txtNgayban.getText(),giamGia,txtTonghoadon.getText(),cthdList).setVisible(true);
        }else{
            JOptionPane.showMessageDialog(rootPane, "BẠN CHƯA ẤN THANH TOÁN!");
        }
        

    }//GEN-LAST:event_btnThanhtoanActionPerformed

    private void txtMahdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMahdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMahdActionPerformed

    private void txtDiemtichluyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemtichluyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemtichluyActionPerformed
    public void selectedCTHD(String masp,int soluong){
        boolean isExisted=false;
        int vitritrung=-1;
        for(int i=0;i<cthdList.size();i++){
            if(cthdList.get(i).getMaSP().compareTo(masp)==0){
                isExisted=true;
                vitritrung=i;
            }
        }
        if(isExisted==false){
            TaoCode code=new TaoCode();
            String maCTHD=txtMahd.getText()+"CT"+code.createIdCTHD(cthdList);
            SanPham sp=SanPhamModify.findByID(masp);
            int SL=soluong;
            int thanhtien=SL*sp.getGiaXuat();
            ChiTietHoaDon cthd=new ChiTietHoaDon(maCTHD,txtMahd.getText(),sp.getMaSP(),SL,thanhtien);
            cthdList.add(cthd);
        }else{
            SanPham sp=SanPhamModify.findByID(masp);
            int soluongcu=cthdList.get(vitritrung).getSoLuong();
            int soluongmoi=soluongcu+soluong;
            if(soluongmoi>sp.getSoLuong()){
                JOptionPane.showMessageDialog(rootPane,"KHÔNG ĐỦ SỐ LƯỢNG SẢN PHẨM");
            }else{
            cthdList.get(vitritrung).setSoLuong(soluongmoi);
            cthdList.get(vitritrung).setThanhTien(soluongmoi*sp.getGiaXuat());

            }
        }
    }
    public void tinhTienCTHD(List<ChiTietHoaDon> cthdList){
        int tongcthd=0;    
        for(int i=0;i<cthdList.size();i++){
            tongcthd+=cthdList.get(i).getThanhTien();
        }
        txtTongcong.setText(""+tongcthd);    
    }
    private void txtTongcongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongcongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongcongActionPerformed

    private void btnMakmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakmActionPerformed
        // TODO add your handling code here:
        INPUTMAKMFORM inputMakm=new INPUTMAKMFORM(this,rootPaneCheckingEnabled);
        inputMakm.setVisible(true);
    }//GEN-LAST:event_btnMakmActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        int option=JOptionPane.showConfirmDialog(this,"BẠN CÓ CHẮC CHẮN MUỐN HỦY HÓA ĐƠN NÀY ?");
        if(option==0){
        List<ChiTietHoaDon> cthdList=ChiTietHoaDonModify.findByMaHD(txtMahd.getText());
        for(int i=0;i<cthdList.size();i++){
            ChiTietHoaDonModify.delete(cthdList.get(i).getMaCTHD());
        }
        HoaDonModify.delete(txtMahd.getText());
        }
        this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void tblCthdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCthdMouseClicked
        // TODO add your handling code here:
        selectedIndex=tblCthd.getSelectedRow();    
    }//GEN-LAST:event_tblCthdMouseClicked

    private void btnThanhtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhtienActionPerformed
        // TODO add your handling code here:
        int giamgia=0;
        int diemtichluy=0;
        int tonghoadon=Integer.parseInt(txtTongcong.getText());
        if(txtMakm.getText().length()>0){
            MaKM km=MaKmModify.findByID(txtMakm.getText());
            int value=km.getGiaTri();
            giamgia=(tonghoadon*value)/100;
        }
        if(checkDiemtichluy.isSelected()){
            diemtichluy=Integer.parseInt(txtDiemtichluy.getText());
        }    
        tonghoadon=tonghoadon-giamgia-diemtichluy;
        giamGia=giamgia+diemtichluy;
        txtTonghoadon.setText(""+tonghoadon);
       
    }//GEN-LAST:event_btnThanhtienActionPerformed

    private void btnSanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanphamActionPerformed
        // TODO add your handling code here:
        InputSPFORM input=new InputSPFORM(this,rootPaneCheckingEnabled,txtMahd.getText());
        input.setVisible(true);

    }//GEN-LAST:event_btnSanphamActionPerformed
    
    public void selectedMaKM(String makm){
        txtMakm.setText(makm);
    }
    public void addCTHD(ChiTietHoaDon cthd){
        cthdList.add(cthd);
    }
    
    public void getListCTHD(List<ChiTietHoaDon> cthdListInput){
        for(int i=0;i<cthdListInput.size();i++){
            cthdList.add(cthdListInput.get(i));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CHITIETHOADONFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CHITIETHOADONFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CHITIETHOADONFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CHITIETHOADONFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CHITIETHOADONFORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnMakm;
    private javax.swing.JButton btnSanpham;
    private javax.swing.JButton btnThanhtien;
    private javax.swing.JButton btnThanhtoan;
    private javax.swing.JCheckBox checkDiemtichluy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCthd;
    private javax.swing.JLabel txtChucvu;
    private javax.swing.JTextField txtDiemtichluy;
    private javax.swing.JTextField txtMahd;
    private javax.swing.JTextField txtMakh;
    private javax.swing.JTextField txtMakm;
    private javax.swing.JTextField txtNgayban;
    private javax.swing.JTextField txtTenkh;
    private javax.swing.JTextField txtTongcong;
    private javax.swing.JTextField txtTonghoadon;
    // End of variables declaration//GEN-END:variables
}
