/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORM;

import Code.ChiTietHoaDon;
import Code.ChiTietHoaDonModify;
import Code.HoaDon;
import Code.HoaDonModify;
import Code.SanPhamModify;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class DANHSACHCHITIETHOADON extends javax.swing.JFrame {
    
      DefaultTableModel tableModel;
      int selectedIndex=-1;
      String maHD;
      String chucvu;
    /**
     * Creates new form DANHSACHCHITIETHOADON
     */
    public DANHSACHCHITIETHOADON() {
        initComponents();
        this.setLocationRelativeTo(null);
        tableModel=(DefaultTableModel) tblCthd.getModel();
        showCTHD();
    }   
    
    public DANHSACHCHITIETHOADON(String Chucvu) {
        initComponents();
        this.setLocationRelativeTo(null);
        txtChucvu.setText(Chucvu);
        chucvu=Chucvu;
        tableModel=(DefaultTableModel) tblCthd.getModel();
        showCTHD();
    }
    private void showCTHD(){
        List<ChiTietHoaDon> cthdList=ChiTietHoaDonModify.findAll();
        tableModel.setRowCount(0);
        cthdList.forEach(cthd->{
            tableModel.addRow(new Object[]{
                cthd.getMaHD(),cthd.getMaCTHD(),cthd.getMaSP(),
                SanPhamModify.findByID(cthd.getMaSP()).getTenSP(),cthd.getSoLuong(),
                SanPhamModify.findByID(cthd.getMaSP()).getGiaXuat(),cthd.getThanhTien()
           });
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnQuaylai = new javax.swing.JButton();
        txt = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTimkiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCthd = new javax.swing.JTable();
        txtNgaybd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNgaykt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtChucvu = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnHoadon = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        btnQuaylai.setBackground(new java.awt.Color(255, 0, 0));
        btnQuaylai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Back(1).png"))); // NOI18N
        btnQuaylai.setText("QUAY LẠI");
        btnQuaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuaylaiActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("DANH SÁCH CHI TIẾT HOÁ ĐƠN BÁN HÀNG");

        btnTimkiem.setBackground(new java.awt.Color(255, 255, 0));
        btnTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Find(1).png"))); // NOI18N
        btnTimkiem.setText("TÌM KIẾM");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        tblCthd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MAHD", "MACTHD", "MASP", "TENSP", "SOLUONG", "GIABAN", "THANHTIEN"
            }
        ));
        tblCthd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCthdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCthd);

        txtNgaybd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaybdActionPerformed(evt);
            }
        });

        jLabel2.setText("NGÀY KẾT THÚC");

        jLabel3.setText("NGÀY BẮT ĐẦU");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Chức vụ :");

        txtChucvu.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txtChucvu.setText("jLabel3");

        btnReset.setText("Lam moi");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnHoadon.setText("XEM HOA DON");
        btnHoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoadonActionPerformed(evt);
            }
        });

        jButton1.setText("QUAY LAI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txtLayout = new javax.swing.GroupLayout(txt);
        txt.setLayout(txtLayout);
        txtLayout.setHorizontalGroup(
            txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(txtLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(txtLayout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtChucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(txtLayout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(txtLayout.createSequentialGroup()
                        .addGroup(txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(txtLayout.createSequentialGroup()
                                .addGroup(txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNgaybd, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                                    .addComponent(txtNgaykt))
                                .addGap(47, 47, 47)
                                .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        txtLayout.setVerticalGroup(
            txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtChucvu))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgaybd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgaykt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnReset))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHoadon)
                    .addComponent(jButton1))
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNgaybdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaybdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaybdActionPerformed

    private void btnQuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuaylaiActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MENUFORM(txtChucvu.getText()).setVisible(true);
    }//GEN-LAST:event_btnQuaylaiActionPerformed

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        // TODO add your handling code here:
        
        boolean isOK=true;   
        List<HoaDon> hdList=HoaDonModify.findListHdByDate(txtNgaybd.getText(), txtNgaykt.getText());
        try{
        Date date=Date.valueOf(txtNgaybd.getText());
        }
        catch(java.lang.IllegalArgumentException ex){
            JOptionPane.showMessageDialog(rootPane, "NHẬP SAI ĐỊNH DẠNG NGÀY BẮT ĐẦU(YYYY-MM-DD)!");
            isOK=false;
        }
        try{
        Date date=Date.valueOf(txtNgaykt.getText());
        }
        catch(java.lang.IllegalArgumentException ex){
            JOptionPane.showMessageDialog(rootPane, "NHẬP SAI ĐỊNH DẠNG NGÀY KẾT THÚC (YYYY-MM-DD)!");
            isOK=false;
        }
        if(isOK){
        List<ChiTietHoaDon> cthdList1=new ArrayList<>();
        List<ChiTietHoaDon> cthdList2=new ArrayList<>();
        if(hdList.size()>0){
   
        for(int i=0;i<hdList.size();i++){
            cthdList2=ChiTietHoaDonModify.findByMaHD(hdList.get(i).getMaHD());
            if(cthdList2.size()>1){
                for(int j=0;j<cthdList2.size();j++){
                    cthdList1.add(cthdList2.get(j));
                }
            }else{
                cthdList1.add(cthdList2.get(0));
            }
        }
        tableModel.setRowCount(0);
        cthdList1.forEach(cthd->{   
            tableModel.addRow(new Object[]{
                cthd.getMaHD(),cthd.getMaCTHD(),cthd.getMaSP(),
                SanPhamModify.findByID(cthd.getMaSP()).getTenSP(),cthd.getSoLuong(),
                SanPhamModify.findByID(cthd.getMaSP()).getGiaXuat(),cthd.getThanhTien()
           });
        });
        }else{
            JOptionPane.showMessageDialog(rootPane,"KHÔNG CÓ HÓA ĐƠN NÀO PHÙ HỢP!");
            showCTHD();
        }
        }
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtNgaybd.setText("");
        txtNgaykt.setText("");
        showCTHD();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblCthdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCthdMouseClicked
        // TODO add your handling code here:
        selectedIndex=tblCthd.getSelectedRow();
        maHD=(String) tblCthd.getValueAt(selectedIndex,0);         
    }//GEN-LAST:event_tblCthdMouseClicked

    private void btnHoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoadonActionPerformed
        // TODO add your handling code here:
        if(selectedIndex>=0){
           new QUANLYHOADONFORM(maHD,chucvu).setVisible(true);
           this.dispose();
        }else{
            JOptionPane.showMessageDialog(rootPane, "VUI LÒNG CHỌN 1 CHI TIẾT HÓA ĐƠN TRONG BẢNG !");
        }
    }//GEN-LAST:event_btnHoadonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          this.dispose();
        new MENUFORM(txtChucvu.getText()).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DANHSACHCHITIETHOADON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DANHSACHCHITIETHOADON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DANHSACHCHITIETHOADON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DANHSACHCHITIETHOADON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DANHSACHCHITIETHOADON().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHoadon;
    private javax.swing.JButton btnQuaylai;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCthd;
    private javax.swing.JPanel txt;
    private javax.swing.JLabel txtChucvu;
    private javax.swing.JTextField txtNgaybd;
    private javax.swing.JTextField txtNgaykt;
    // End of variables declaration//GEN-END:variables
}
