/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORM;


import Code.NhaCC;
import Code.NhaCCModify;
import Code.SanPham;
import Code.SanPhamModify;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class HANGFORM extends javax.swing.JFrame {

     DefaultTableModel tableModel;
   
    int selectedIndex=-1;
    /**
     * Creates new form HANGFORM
     */
    public HANGFORM() {
        initComponents();
        this.setLocationRelativeTo(null);
        tableModel=(DefaultTableModel) tblNcc.getModel();
        showInfo();
        showNcc();
    }
    public HANGFORM(String ChucVu) {
        initComponents();
           this.setLocationRelativeTo(null);
        showInfo();
        tableModel=(DefaultTableModel) tblNcc.getModel();
        showNcc();
        txtChucvu.setText(ChucVu);
    }
    
    private void showNcc(){
        List<NhaCC> nccList=NhaCCModify.findAll();
        tableModel.setRowCount(0);
        nccList.forEach(ncc -> {
            tableModel.addRow(new Object[] {ncc.getMaNCC(),
                ncc.getTenNCC(),ncc.getSdt(),ncc.getDiaChi()     
            });
           
        });
    }
    private void showSelectedRow(){
        List<NhaCC> nccList=NhaCCModify.findAll();
        selectedIndex=tblNcc.getSelectedRow();
       
        if(selectedIndex>=0){
            NhaCC ncc=nccList.get(selectedIndex);
            txtMancc.setText(ncc.getMaNCC());
            txtTenncc.setText(ncc.getTenNCC());
            txtDiachi.setText(ncc.getDiaChi());
            txtSdt.setText(ncc.getSdt());
        }
    }
    private void showInfo(){
       List<NhaCC> nccList=NhaCCModify.findAll();
    
       try{
           NhaCC ncc=nccList.get(nccList.size()-1);
            txtMancc.setText(ncc.getMaNCC());
            txtTenncc.setText(ncc.getTenNCC());
            txtDiachi.setText(ncc.getDiaChi());
            txtSdt.setText(ncc.getSdt());
           
       }catch(Exception ex){
           txtMancc.setText("");
            txtTenncc.setText("");
            txtDiachi.setText("");
            txtSdt.setText("");
       }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMancc = new javax.swing.JTextField();
        txtTenncc = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNcc = new javax.swing.JTable();
        btnFind = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDiachi = new javax.swing.JTextField();
        btnQuaylai = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtChucvu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("QUẢN LÍ NHÀ CUNG CẤP");

        jLabel2.setText("MÃ HÃNG");

        jLabel3.setText("TÊN HÃNG");

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Refresh(1).png"))); // NOI18N
        btnReset.setText("LÀM MỚI");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 204, 0));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Save(1).png"))); // NOI18N
        btnSave.setText("LƯU");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 255, 0));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Repair(1).png"))); // NOI18N
        btnUpdate.setText("SỬA");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Delete(1).png"))); // NOI18N
        btnDelete.setText("XÓA");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblNcc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MÃ HÃNG", "TÊN HÃNG", "SDT", "DIACHI"
            }
        ));
        tblNcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNccMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNcc);

        btnFind.setBackground(new java.awt.Color(255, 204, 0));
        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Find(1).png"))); // NOI18N
        btnFind.setText("TÌM KIẾM");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        jLabel4.setText("SDT");

        jLabel5.setText("ĐỊA CHỈ");

        btnQuaylai.setBackground(new java.awt.Color(255, 0, 0));
        btnQuaylai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Back(1).png"))); // NOI18N
        btnQuaylai.setText("QUAY LẠI");
        btnQuaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuaylaiActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("Chức vụ :");

        txtChucvu.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txtChucvu.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnQuaylai)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTenncc)
                            .addComponent(txtMancc, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(txtSdt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDiachi, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtChucvu))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnReset)
                                    .addComponent(txtMancc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSave)
                                    .addComponent(txtTenncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(btnUpdate)
                            .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(53, 53, 53)
                        .addComponent(btnFind))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(btnQuaylai)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        
        txtMancc.setText("");
        txtTenncc.setText("");
        txtDiachi.setText("");
        txtSdt.setText("");
       
        showNcc();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String maNcc=txtMancc.getText();
        String tenNcc=txtTenncc.getText();
        String diaChi=txtDiachi.getText();
        String sdt=txtSdt.getText();
        boolean isOK=true;
        try{
            Double.parseDouble(sdt);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "SỐ ĐIỆN THOẠI KHÔNG ĐƯỢC CHỨA KÍ TỰ HOẶC ĐỂ TRỐNG !");
            isOK=false;
        }
        if(NhaCCModify.compareByID(maNcc)){
            JOptionPane.showMessageDialog(rootPane, "MÃ NHÀ CUNG CẤP ĐÃ TỒN TẠI!");
            isOK=false;
            
        }
        if(isOK){
        NhaCC ncc=new NhaCC(maNcc,tenNcc,sdt,diaChi);
        
        NhaCCModify.insert(ncc);
        JOptionPane.showMessageDialog(rootPane, "LƯU THÀNH CÔNG!");
        }
        showNcc();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String maNcc=txtMancc.getText();
        String tenNcc=txtTenncc.getText();
        String diaChi=txtDiachi.getText();
        String sdt=txtSdt.getText();
        
       NhaCC ncc=new NhaCC(maNcc,tenNcc,sdt,diaChi);
        
        NhaCCModify.update(ncc);
        JOptionPane.showMessageDialog(rootPane, "CẬP NHẬT THÀNH CÔNG!");
        showNcc();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(txtChucvu.getText().compareTo("QL")==0){
            
        //    List<NhaCC> nccList=NhaCCModify.findAll();
            selectedIndex=tblNcc.getSelectedRow();
       
            if(selectedIndex>=0){
                String ncc=(String) tblNcc.getValueAt(selectedIndex, 0);
                int option=JOptionPane.showConfirmDialog(this, "BẠN CÓ CHẮC CHẮN MUỐN XÓA NHÀ CUNG CẤP NÀY ?");
                         
                if(option==0){
//                    List<SanPham> spList=SanPhamModify.findAll();
//                    for(int i=0;i<spList.size();i++){
//                        if(spList.get(i).getMaNCC().compareTo(ncc)==0){
//                            SanPhamModify.delete(spList,);
//                        }
//                    }
                    NhaCCModify.delete(ncc);
                    JOptionPane.showMessageDialog(rootPane, "XÓA THÀNH CÔNG!");
                    showNcc();
                    showInfo();
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "BẠN KHÔNG PHẢI QUẢN LÍ");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        String input =JOptionPane.showInputDialog(this,"NHẬP TÊN NHÀ CUNG CẤP CẦN TÌM KIẾM:");
        if(input!=null&&input.length()>0){
            List<NhaCC> nccList=NhaCCModify.findByName(input);
            
            tableModel.setRowCount(0);
            nccList.forEach(ncc -> {
            tableModel.addRow(new Object[] {ncc.getMaNCC(),
                ncc.getTenNCC(),ncc.getSdt(),ncc.getDiaChi()
            });
           
        });
        }else{
            showNcc();
    }                     
    }//GEN-LAST:event_btnFindActionPerformed

    private void tblNccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNccMouseClicked
        // TODO add your handling code here:
        showSelectedRow();
    }//GEN-LAST:event_tblNccMouseClicked

    private void btnQuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuaylaiActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MENUFORM(txtChucvu.getText()).setVisible(true); 
    }//GEN-LAST:event_btnQuaylaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HANGFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HANGFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HANGFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HANGFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HANGFORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnQuaylai;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNcc;
    private javax.swing.JLabel txtChucvu;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtMancc;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTenncc;
    // End of variables declaration//GEN-END:variables
}
