/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORM;

import Code.ChiTietHoaDon;
import Code.LoaiSPModify;
import Code.LoaiSanPham;
import Code.NhaCCModify;
import Code.SanPham;
import Code.SanPhamModify;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class InputSPFORM extends javax.swing.JDialog {

    DefaultTableModel tableModel;
    String mahd;
//    List<SanPham> spList=new ArrayList<>();
    List<ChiTietHoaDon> cthdList=new ArrayList<>();
    int selectedIndex=-1;
    /**
     * Creates new form InputSPFORM
     */
    private CHITIETHOADONFORM chitiet;
    public InputSPFORM(java.awt.Frame parent, boolean modal,String maHD) {
        super(parent, modal);
        initComponents();
        this.setLocation(1100,300);
        tableModel=(DefaultTableModel) tblSanpham.getModel();
        chitiet=(CHITIETHOADONFORM) parent;
        mahd=maHD;
        showSanPham();
        showComboLoaiSP();
    }
    private void showSanPham(){
        List<SanPham> spList=SanPhamModify.findAll();
        tableModel.setRowCount(0);
        spList.forEach(sp -> {
            tableModel.addRow(new Object[] {sp.getMaSP(),
                sp.getTenSP(),LoaiSPModify.findByID(sp.getMaLoaiSP()).getTenLoaiSP(),
                sp.getGiaXuat(),NhaCCModify.findByID(sp.getMaNCC()).getTenNCC()
                ,sp.getSoLuong()          
            });
           
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanpham = new javax.swing.JTable();
        btnChon = new javax.swing.JButton();
        btnTimkiem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTensp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbLoaisp = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("DANH SACH SAN PHAM");

        tblSanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MASP", "TENSP", "LOAISP", "GIABAN", "HANG", "SOLUONG"
            }
        ));
        jScrollPane1.setViewportView(tblSanpham);

        btnChon.setText("THEM VAO HOA DON");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });

        btnTimkiem.setText("TIMKIEM");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        jLabel2.setText("Loai san pham");

        jLabel3.setText("Ten san pham");

        jButton1.setText("HOAN THANH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTensp)
                            .addComponent(cbLoaisp, 0, 129, Short.MAX_VALUE))
                        .addGap(146, 146, 146)
                        .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChon)))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimkiem)
                    .addComponent(jLabel2)
                    .addComponent(cbLoaisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnChon))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        // TODO add your handling code here:  
        boolean isOK=true;
        SanPham sp=new SanPham();
        int soluong=0;
        selectedIndex=tblSanpham.getSelectedRow();
        if(selectedIndex>=0){
            String maSP=(String) tblSanpham.getValueAt(selectedIndex,0);      
            sp=SanPhamModify.findByID(maSP);
            String input=JOptionPane.showInputDialog(rootPane,"NHẬP SỐ LƯƠNG SẢN PHẨM:");
            try{
                soluong=Integer.parseInt(input);
            }catch(Exception ex){
                JOptionPane.showMessageDialog(rootPane, "SỐ LƯỢNG SẢN PHẨM PHẢI LÀ SỐ !");
                isOK=false;
            }
            if(soluong<=0){
                JOptionPane.showMessageDialog(rootPane, "SỐ LƯỢNG SẢN PHẨM PHẢI LỚN HƠN 0 !");
                isOK=false;
            }
            if(soluong>sp.getSoLuong()){
                isOK=false;
                JOptionPane.showMessageDialog(rootPane, "KHÔNG ĐỦ SỐ LƯỢNG SẢN PHẨM!");
            }
            if(isOK){
            chitiet.selectedCTHD(maSP, soluong);
            chitiet.showCTHD();
            chitiet.tinhTienCTHD();
            }

        }else{
            JOptionPane.showMessageDialog(rootPane,"VUI LÒNG CHỌN 1 SẢN PHẨM !");
        }     
    }//GEN-LAST:event_btnChonActionPerformed

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        // TODO add your handling code here:
        List<SanPham> spList=new ArrayList<>();
        LoaiSanPham lsp=LoaiSPModify.findByExName((String) cbLoaisp.getSelectedItem());
        if(txtTensp.getText().length()<=0){
            spList=SanPhamModify.findByMaLoaiSP(lsp.getMaLoaiSP());
        }else{
             spList=SanPhamModify.findByMaLSPtenSP(lsp.getMaLoaiSP(),txtTensp.getText());
        }
            tableModel.setRowCount(0);
            spList.forEach(sp -> {
            tableModel.addRow(new Object[] {sp.getMaSP(),
            sp.getTenSP(),LoaiSPModify.findByID(sp.getMaLoaiSP()).getTenLoaiSP(),
            sp.getGiaXuat(),NhaCCModify.findByID(sp.getMaNCC()).getTenNCC()
            ,sp.getSoLuong()          
            }); 
        });  
         
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<cthdList.size();i++){
            System.out.println(i);
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
     private void showComboLoaiSP(){
        List<LoaiSanPham> loaiSP=LoaiSPModify.findAll();
       
        for(LoaiSanPham sp:loaiSP){
            cbLoaisp.addItem(sp.getTenLoaiSP());
        }
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JComboBox<String> cbLoaisp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSanpham;
    private javax.swing.JTextField txtTensp;
    // End of variables declaration//GEN-END:variables
}
