/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORM;

import Code.KhachHang;
import Code.KhachHangModify;
import Code.TaoCode;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class KHACHHANGFORM extends javax.swing.JFrame {

    DefaultTableModel tableModel;
   
    int selectedIndex=-1;
    /**
     * Creates new form KHACHHANGFORM
     */
    public KHACHHANGFORM() {
        initComponents();
           this.setLocationRelativeTo(null);
        tableModel=(DefaultTableModel) tblKhachHang.getModel();
        showInfo();
        showKhachHang();
    }
    
    public KHACHHANGFORM(String ChucVu) {
        initComponents();
           this.setLocationRelativeTo(null);
        showInfo();
        tableModel=(DefaultTableModel) tblKhachHang.getModel();
        showKhachHang();
        txtChucVu.setText(ChucVu);
        
    }
     private void showKhachHang(){
        List<KhachHang> khachHangList=KhachHangModify.findAll();
        tableModel.setRowCount(0);
        khachHangList.forEach(kh -> {
            tableModel.addRow(new Object[] {kh.getMaKH(),
                kh.getTenKH(),kh.getDiaChi(),kh.getSdt(),
                kh.getDiemTichLuy()
            });
           
        });
    }
    private void showSelectedRow(){
        selectedIndex=tblKhachHang.getSelectedRow();    
        if(selectedIndex>=0){
                String makh=(String) tblKhachHang.getValueAt(selectedIndex,0);
                KhachHang kh=KhachHangModify.findByID(makh);
                txtMakh.setText(makh);                
                txtTenkh.setText(kh.getTenKH());             
                txtDiachi.setText(kh.getDiaChi());              
                txtSdt.setText(kh.getSdt());
                txtDiemtichluy.setText(""+kh.getDiemTichLuy());
            }
        else{
            showKhachHang();
        }
            
    }
    private void showInfo(){
       List<KhachHang> khList=KhachHangModify.findAll();
    
       try{
           KhachHang kh=khList.get(khList.size()-1);
            txtMakh.setText(kh.getMaKH());
            txtTenkh.setText(kh.getTenKH());
            txtDiachi.setText(kh.getDiaChi());
            txtSdt.setText(kh.getSdt());
            txtDiemtichluy.setText(""+kh.getDiemTichLuy());
       }catch(Exception ex){
           txtMakh.setText("");
           txtTenkh.setText("");
           txtDiachi.setText("");
           txtSdt.setText("");
           txtDiemtichluy.setText("");
       }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMakh = new javax.swing.JTextField();
        txtTenkh = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnQuaylai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtChucVu = new javax.swing.JLabel();
        diemtichluy = new javax.swing.JLabel();
        txtDiemtichluy = new javax.swing.JTextField();
        tbnHoadon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("KHÁCH HÀNG");

        jLabel2.setText("MÃ KH");

        jLabel3.setText("TÊN KH");

        jLabel4.setText("ĐỊA CHỈ");

        jLabel5.setText("SỐ ĐT");

        txtMakh.setEditable(false);

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Refresh(1).png"))); // NOI18N
        btnReset.setText("THEM MOI");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 255, 0));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Save(1).png"))); // NOI18N
        btnSave.setText("LƯU");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Delete(1).png"))); // NOI18N
        btnDelete.setText("XÓA");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Find(1).png"))); // NOI18N
        btnFind.setText("TÌM KIẾM");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnQuaylai.setBackground(new java.awt.Color(255, 102, 0));
        btnQuaylai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Back(1).png"))); // NOI18N
        btnQuaylai.setText("QUAY LẠI");
        btnQuaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuaylaiActionPerformed(evt);
            }
        });

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MAKH", "TENKH", "DIACHI", "SDT", "DIEMTICHLUY"
            }
        ));
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachHang);

        btnUpdate.setBackground(new java.awt.Color(255, 255, 0));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Repair(1).png"))); // NOI18N
        btnUpdate.setText("SỬA");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("Chức vụ :");

        txtChucVu.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txtChucVu.setText("jLabel3");

        diemtichluy.setText("DIEM TICH LUY");

        txtDiemtichluy.setEditable(false);

        tbnHoadon.setText("TAO HOA DON");
        tbnHoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnHoadonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnQuaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbnHoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(diemtichluy, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMakh, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(txtTenkh)
                                    .addComponent(txtDiachi)
                                    .addComponent(txtSdt)
                                    .addComponent(txtDiemtichluy))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(47, 47, 47)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtChucVu)))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMakh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnReset)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUpdate)
                                    .addComponent(jLabel3))))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSave)
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete)
                            .addComponent(jLabel5))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiemtichluy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diemtichluy))
                        .addGap(33, 33, 33)
                        .addComponent(btnFind)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuaylai)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(tbnHoadon)
                        .addGap(33, 33, 33))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        TaoCode code=new TaoCode();
        boolean isExisted=false;
        String maKh;
        do{
            maKh=code.randomAlphaNumeric(4);
            isExisted=KhachHangModify.compareByID(maKh);
        }while(isExisted);
        txtMakh.setText(maKh);
        txtTenkh.setText("");
        txtDiachi.setText("");
        txtSdt.setText("");
        txtDiemtichluy.setText("0");
        showKhachHang();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnQuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuaylaiActionPerformed
       this.dispose();
        new MENUFORM(txtChucVu.getText()).setVisible(true); 
    }//GEN-LAST:event_btnQuaylaiActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String maKH=txtMakh.getText();
        String tenKH=txtTenkh.getText();
        String diaChi=txtDiachi.getText();
        String sdt=txtSdt.getText();
        int diemtichluy=0;
        boolean isOK=true;
        try{
            Double.parseDouble(sdt);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "SỐ ĐIỆN THOẠI KHÔNG ĐƯỢC CHỨA KÍ TỰ HOẶC BỎ TRỐNG!");
            isOK=false;
        }
        if(txtTenkh.getText()==null||txtTenkh.getText().length()<=0){
            JOptionPane.showMessageDialog(rootPane, "VUI LÒNG NHẬP TÊN KHÁCH HÀNG!");
            isOK=false;
        }
        if(KhachHangModify.compareByID(maKH)){
            JOptionPane.showMessageDialog(rootPane, "MÃ KHÁCH HÀNG ĐÃ TỒN TẠI!");
            isOK=false;
            
        }
        if(isOK){
        KhachHang kh=new KhachHang(maKH,tenKH,diaChi,sdt,diemtichluy);
        
        KhachHangModify.insert(kh);
        JOptionPane.showMessageDialog(rootPane, "LƯU THÀNH CÔNG!");
        }
        showKhachHang();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        List<KhachHang> khachHangList=KhachHangModify.findAll();
        selectedIndex=tblKhachHang.getSelectedRow();
       
        if(selectedIndex>=0){
            KhachHang kh=khachHangList.get(selectedIndex);
            
            int option=JOptionPane.showConfirmDialog(this, "BẠN CÓ MUỐN XÓA KHÁCH HÀNG NÀY?");
          
            
            if(option==0){
              KhachHangModify.delete(kh.getMaKH());
              JOptionPane.showMessageDialog(rootPane, "XÓA THÀNH CÔNG!");
              showKhachHang();
              showInfo();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
          String input =JOptionPane.showInputDialog(this,"NHẬP TÊN KHÁCH HÀNG CẦN TÌM KIẾM:");
        if(input!=null&&input.length()>0){
            List<KhachHang> khachHangList=KhachHangModify.findByName(input);
            
            tableModel.setRowCount(0);
            khachHangList.forEach(kh -> {
            tableModel.addRow(new Object[] {kh.getMaKH(),
                kh.getTenKH(),kh.getDiaChi(),kh.getSdt(),
                kh.getDiemTichLuy()
            });
           
        });
        }else{
            showKhachHang();
    }//GEN-LAST:event_btnFindActionPerformed
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String maKH=txtMakh.getText();
        String tenKH=txtTenkh.getText();
        String diaChi=txtDiachi.getText();
        String sdt=txtSdt.getText();
        int diemtichluy=Integer.parseInt(txtDiemtichluy.getText());
        
        KhachHang kh=new KhachHang(maKH,tenKH,diaChi,sdt,diemtichluy);
        
        KhachHangModify.update(kh);
        JOptionPane.showMessageDialog(rootPane, "CẬP NHẬT THÀNH CÔNG!");
        showKhachHang();
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        // TODO add your handling code here:
        showSelectedRow();
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void tbnHoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnHoadonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TaoCode code=new TaoCode();
        String iD=code.createIdHD();       
        new HOADONFORM(txtChucVu.getText(),txtMakh.getText(),iD).setVisible(true);
    }//GEN-LAST:event_tbnHoadonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KHACHHANGFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KHACHHANGFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KHACHHANGFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KHACHHANGFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KHACHHANGFORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnQuaylai;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel diemtichluy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JButton tbnHoadon;
    private javax.swing.JLabel txtChucVu;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtDiemtichluy;
    private javax.swing.JTextField txtMakh;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTenkh;
    // End of variables declaration//GEN-END:variables
}
