/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORM;

import Code.MaKM;
import Code.MaKmModify;
import Code.TaoCode;
import java.sql.Date;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class KHUYENMAIFORM extends javax.swing.JFrame {
    DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    
    DefaultTableModel tableModel;   
    int selectedIndex=-1;
    /**
     * Creates new form KHUYENMAIFORM
     */
    public KHUYENMAIFORM() {
        initComponents();
           this.setLocationRelativeTo(null);
        tableModel=(DefaultTableModel) tblMakm.getModel();
        showInfo();
        showMakm();
        
    }
    public KHUYENMAIFORM(String chucvu){
        initComponents();
           this.setLocationRelativeTo(null);
        tableModel=(DefaultTableModel) tblMakm.getModel();
        txtChucvu.setText(chucvu);
        showInfo();
        showMakm();
    }
    private void showInfo(){
          List<MaKM> kmList=MaKmModify.findAll();
    
       try{
            MaKM km=kmList.get(kmList.size()-1);
            txtMakm.setText(km.getMaKM());
            txtGiatri.setText(""+km.getGiaTri());
            txtNgaybd.setText(""+km.getNgayBD());
            txtNgaykt.setText(""+km.getNgayKT());
            txtNoidung.setText(km.getGhiChu());
       }catch(Exception ex){
            txtMakm.setText("");
            txtGiatri.setText("");
            txtNgaybd.setText("");
            txtNgaykt.setText("");
            txtNoidung.setText("");
       }
    }
    private void showMakm(){
        List<MaKM> kmList=MaKmModify.findAll();
        tableModel.setRowCount(0);
        kmList.forEach(km -> {
            tableModel.addRow(new Object[] {km.getMaKM(),
                km.getGiaTri(),km.getNgayBD(),
                km.getNgayKT(),km.getGhiChu()
            });          
        });
    }
    private void showSelectedRow(){
        List<MaKM> kmList=MaKmModify.findAll();
        selectedIndex=tblMakm.getSelectedRow();
       
        if(selectedIndex>=0){
            MaKM km=kmList.get(selectedIndex);
            txtMakm.setText(km.getMaKM());
            txtGiatri.setText(""+km.getGiaTri());
            txtNgaybd.setText(""+km.getNgayBD());
            txtNgaykt.setText(""+km.getNgayKT());
            txtNoidung.setText(km.getGhiChu());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        giatri = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMakm = new javax.swing.JTextField();
        txtGiatri = new javax.swing.JTextField();
        txtNgaybd = new javax.swing.JTextField();
        txtNgaykt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMakm = new javax.swing.JTable();
        btnReset = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnQuaylai = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtChucvu = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNoidung = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        jLabel1.setBackground(new java.awt.Color(153, 0, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("QUẢN LÍ KHUYẾN MÃI");

        jLabel3.setText("MÃ KM");

        giatri.setText("Giá trị");

        jLabel5.setText("NGÀY BẮT ĐẦU");

        jLabel6.setText("NGÀY KẾT THÚC");

        txtMakm.setEditable(false);

        tblMakm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MÃ KM", "GIÁ TRỊ", "NGÀY BẮT ĐẦU", "NGÀY KẾT THÚC", "NỘI DUNG"
            }
        ));
        tblMakm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMakmMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMakm);
        if (tblMakm.getColumnModel().getColumnCount() > 0) {
            tblMakm.getColumnModel().getColumn(0).setResizable(false);
            tblMakm.getColumnModel().getColumn(1).setResizable(false);
        }

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Refresh(1).png"))); // NOI18N
        btnReset.setText("LÀM MỚI");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 255, 0));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Save(1).png"))); // NOI18N
        btnSave.setText("LƯU");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 0, 51));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Delete(1).png"))); // NOI18N
        btnDelete.setText("XÓA");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnQuaylai.setBackground(new java.awt.Color(255, 51, 0));
        btnQuaylai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Back(1).png"))); // NOI18N
        btnQuaylai.setText("QUAY LẠI");
        btnQuaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuaylaiActionPerformed(evt);
            }
        });

        btnFind.setBackground(new java.awt.Color(0, 255, 0));
        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Find(1).png"))); // NOI18N
        btnFind.setText("TÌM KIẾM");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 255, 0));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Repair(1).png"))); // NOI18N
        btnUpdate.setText("SỬA");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("Chức vụ :");

        txtChucvu.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txtChucvu.setText("jLabel3");

        jLabel8.setText("Ghichu");

        jLabel4.setText("(%)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(giatri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMakm, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtGiatri)
                            .addComponent(txtNgaybd)
                            .addComponent(txtNgaykt)
                            .addComponent(txtNoidung))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnQuaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtChucvu))
                    .addComponent(jLabel1))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMakm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset)
                            .addComponent(jLabel3))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtGiatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(giatri)
                                .addComponent(jLabel4))
                            .addComponent(btnSave))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNgaybd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNgaykt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNoidung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(btnFind)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(btnQuaylai))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuaylaiActionPerformed
        this.dispose();
        new MENUFORM(txtChucvu.getText()).setVisible(true);
    }//GEN-LAST:event_btnQuaylaiActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        TaoCode codeKM=new TaoCode();
        String maKM=codeKM.randomAlphaNumericMaKm(12);
        txtMakm.setText(maKM);
        txtGiatri.setText("");
        txtNgaybd.setText("");
        txtNgaykt.setText("");
        txtNoidung.setText("");
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String maKm=txtMakm.getText();
        int giaTri=0;
        String ngayBd=txtNgaybd.getText();
        String ngayKt=txtNgaykt.getText();
        String ghiChu=txtNoidung.getText();
        boolean isOK=true;
    
        if(MaKmModify.compareByID(maKm)){
            JOptionPane.showMessageDialog(rootPane, "MÃ KHUYẾN MẠI NÀY ĐÃ TỒN TẠI !");
            isOK=false;            
        }

        try{
            giaTri=Integer.parseInt(txtGiatri.getText());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "GIÁ TRỊ NÀY PHẢI LÀ SỐ!");
            isOK=false;    
        }
        try{
        Date date=Date.valueOf(txtNgaybd.getText());
        }
        catch(java.lang.IllegalArgumentException ex){
            JOptionPane.showMessageDialog(rootPane, "NHẬP SAI ĐỊNH DẠNG NGÀY BẮT ĐẦU (YYYY-MM-DD)!");
            isOK=false;
        }
        
        try{
        Date date=Date.valueOf(txtNgaykt.getText());
        }
        catch(java.lang.IllegalArgumentException ex){
            JOptionPane.showMessageDialog(rootPane, "NHẬP SAI ĐỊNH DẠNG NGÀY KẾT THÚC (YYYY-MM-DD)!");
            isOK=false;
        }
        if(isOK){
        MaKM km=new MaKM(maKm,giaTri,ghiChu,ngayBd,ngayKt);
        MaKmModify.insert(km);
        JOptionPane.showMessageDialog(rootPane, "LƯU THÀNH CÔNG !");
       }
       
       
        showMakm();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String maKm=txtMakm.getText();
        int giaTri=0;
        String ngayBd=txtNgaybd.getText();
        String ngayKt=txtNgaykt.getText();
        String ghiChu=txtNoidung.getText();
        boolean isOK=true;
   
        
        try{
            giaTri=Integer.parseInt(txtGiatri.getText());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "GIÁ TRỊ PHẢI LÀ SỐ!");
            isOK=false;    
        }
        try{
        Date date=Date.valueOf(txtNgaybd.getText());
        }
        catch(java.lang.IllegalArgumentException ex){
            JOptionPane.showMessageDialog(rootPane, "NHẬP SAI ĐỊNH DẠNG NGÀY BẮT ĐẦU(YYYY-MM-DD)");
            isOK=false;
        }
        
        try{
        Date date=Date.valueOf(txtNgaykt.getText());
        }
        catch(java.lang.IllegalArgumentException ex){
            JOptionPane.showMessageDialog(rootPane, "NHẬP SAI ĐỊNH DẠNG NGÀY KẾT THÚC (YYYY-MM-DD)!");
            isOK=false;
        }
        if(isOK){
        MaKM km=new MaKM(maKm,giaTri,ghiChu,ngayBd,ngayKt);
        MaKmModify.update(km);
        JOptionPane.showMessageDialog(rootPane, "CẬP NHẬT THÀNH CÔNG !");
       }
       
       
        showMakm();
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        List<MaKM> kmList=MaKmModify.findAll();
        selectedIndex=tblMakm.getSelectedRow();
       
        if(selectedIndex>=0){
            MaKM km=kmList.get(selectedIndex);
            
            int option=JOptionPane.showConfirmDialog(this, "BẠN CÓ MUỐN XÓA MÃ KHUYẾN MÃI NÀY?");
          
            
            if(option==0){
              MaKmModify.delete(km.getMaKM());
              JOptionPane.showMessageDialog(rootPane, "XÓA THÀNH CÔNG!");
              showMakm();
              showInfo();
            }
        }
        else{
            MaKmModify.delete(txtMakm.getText());
            JOptionPane.showMessageDialog(rootPane, "XÓA THÀNH CÔNG!");
            showMakm();
            showInfo();
            
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblMakmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMakmMouseClicked
        // TODO add your handling code here:
        showSelectedRow();
    }//GEN-LAST:event_tblMakmMouseClicked

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed

            List<MaKM> kmList=MaKmModify.findByDate();          
            tableModel.setRowCount(0);
            kmList.forEach(km -> {
            tableModel.addRow(new Object[] {km.getMaKM(),
                km.getGiaTri(),km.getNgayBD(),km.getNgayKT(),km.getGhiChu()
            });
           
        });                
    }//GEN-LAST:event_btnFindActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KHUYENMAIFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KHUYENMAIFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KHUYENMAIFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KHUYENMAIFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KHUYENMAIFORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnQuaylai;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel giatri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMakm;
    private javax.swing.JLabel txtChucvu;
    private javax.swing.JTextField txtGiatri;
    private javax.swing.JTextField txtMakm;
    private javax.swing.JTextField txtNgaybd;
    private javax.swing.JTextField txtNgaykt;
    private javax.swing.JTextField txtNoidung;
    // End of variables declaration//GEN-END:variables
}
