/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORM;

import Code.LoaiSPModify;
import Code.LoaiSanPham;
import Code.NhaCC;
import Code.NhaCCModify;
import Code.SanPham;
import Code.SanPhamModify;
import Code.TaoCode;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class SANPHAMFORM extends javax.swing.JFrame {

    DefaultTableModel tableModel;
    List<SanPham> spList=new ArrayList<>();
    int selectedIndex=-1;
    String tenloaisp;
    String tenNhasx;
    /**
     * Creates new form SANPHAMFORM
     */
    public SANPHAMFORM() {
        initComponents();
        this.setLocationRelativeTo(null);
      
        tableModel=(DefaultTableModel) tblSanpham.getModel();
        showInfo();
        showSanPham();
        showComboLoaiSP();
        showComboNcc();
    }
    
     public SANPHAMFORM(String Chucvu) {
        initComponents();
        this.setLocationRelativeTo(null);
           
        txtChucvu.setText(Chucvu);
        tableModel=(DefaultTableModel) tblSanpham.getModel();
        
        showInfo();
     
        showSanPham();
        showComboLoaiSP();
        showComboNcc();
 
    }

    private void showSanPham(){
        List<SanPham> spList=SanPhamModify.findAll();
        tableModel.setRowCount(0);
        spList.forEach(sp -> {
            tableModel.addRow(new Object[] {sp.getMaSP(),
                sp.getTenSP(),
                LoaiSPModify.findByID(sp.getMaLoaiSP()).getTenLoaiSP(),
                NhaCCModify.findByID(sp.getMaNCC()).getTenNCC(),
                sp.getGiaNhap(),sp.getGiaXuat(),
                sp.getDonVi(),sp.getSoLuong()
            });
           
        });
    }
  
    private void showSelectedRow(){
        selectedIndex=tblSanpham.getSelectedRow();
       
        if(selectedIndex>=0){
            String masp=(String) tblSanpham.getValueAt(selectedIndex,0);
            SanPham sp=SanPhamModify.findByID(masp);
            txtMasp.setText(sp.getMaSP());
            txtTensp.setText(sp.getTenSP());
            cbLoaisp.setSelectedItem(LoaiSPModify.findByID(sp.getMaLoaiSP()).getTenLoaiSP());
            cbHangsx.setSelectedItem(NhaCCModify.findByID(sp.getMaNCC()).getTenNCC());
            txtGianhap.setText(""+sp.getGiaNhap());
            txtGiaxuat.setText(""+sp.getGiaXuat());
            cbDonvi.setSelectedItem(sp.getDonVi());
            txtSoluong.setText(""+sp.getSoLuong());
        }
    }
    private void showInfo(){
       List<SanPham> spList=SanPhamModify.findAll();
       
       try{
            SanPham sp=spList.get(spList.size()-1);        
            txtMasp.setText(sp.getMaSP());
            txtTensp.setText(sp.getTenSP());
            cbLoaisp.setSelectedItem(LoaiSPModify.findByID(sp.getMaLoaiSP()).getTenLoaiSP());
            cbHangsx.setSelectedItem(NhaCCModify.findByID(sp.getMaNCC()).getTenNCC());
            txtGianhap.setText(""+sp.getGiaNhap());
            txtGiaxuat.setText(""+sp.getGiaXuat());
            cbDonvi.setSelectedItem(sp.getDonVi());
            txtSoluong.setText(sp.getSoLuong()+"");
       }catch(Exception ex){
            txtMasp.setText("");
            txtTensp.setText("");
            cbLoaisp.setSelectedItem("");
            cbHangsx.setSelectedItem("");
            txtGianhap.setText("");
            txtGiaxuat.setText("");
            cbDonvi.setSelectedItem("");
            txtSoluong.setText("");
       }        
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtMasp = new javax.swing.JTextField();
        txtGiaxuat = new javax.swing.JTextField();
        txtGianhap = new javax.swing.JTextField();
        txtSoluong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanpham = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtTensp = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtChucvu = new javax.swing.JLabel();
        cbDonvi = new javax.swing.JComboBox<>();
        cbLoaisp = new javax.swing.JComboBox<>();
        cbHangsx = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));

        jButton1.setText("jButton1");

        jPanel1.setBackground(new java.awt.Color(102, 255, 153));

        txtMasp.setEditable(false);

        txtGiaxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaxuatActionPerformed(evt);
            }
        });

        tblSanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MASP", "TENSP", "LOAISP", "HANG", "GIANHAP", "GIAXUAT", "DVT", "SLUONG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanpham.setColumnSelectionAllowed(true);
        tblSanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanphamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanpham);
        tblSanpham.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("QUẢN LÍ SẢN PHẨM");

        jLabel2.setText("MÃ SP");

        jLabel3.setText("TÊN SP");

        jLabel4.setText("GIÁ NHẬP");

        jLabel5.setText("Don vi");

        jLabel6.setText("Gia Xuat");

        jLabel7.setText("SỐ LƯỢNG");

        jLabel8.setText("LOẠI SP");

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Refresh(1).png"))); // NOI18N
        btnReset.setText("LÀM MỚI");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(51, 255, 0));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Save(1).png"))); // NOI18N
        btnSave.setText("LƯU");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 51, 0));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Delete(1).png"))); // NOI18N
        btnDelete.setText("XÓA");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Back(1).png"))); // NOI18N
        jButton6.setText("QUAY LẠI");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnFind.setBackground(new java.awt.Color(204, 255, 204));
        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Find(1).png"))); // NOI18N
        btnFind.setText("TÌM KIẾM");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        jLabel9.setText("HÃNG SX");

        btnUpdate.setBackground(new java.awt.Color(255, 255, 0));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Img/Repair(1).png"))); // NOI18N
        btnUpdate.setText("SỬA");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 102));
        jLabel10.setText("Chức vụ :");

        txtChucvu.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txtChucvu.setText("jLabel3");

        cbDonvi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chiếc", "Cái", "Thanh" }));

        cbLoaisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoaispActionPerformed(evt);
            }
        });

        cbHangsx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHangsxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(48, 48, 48)
                            .addComponent(txtMasp, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel8))
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbLoaisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton6)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbHangsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtGiaxuat, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(txtGianhap)
                                    .addComponent(txtSoluong)
                                    .addComponent(cbDonvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtChucvu))
                    .addComponent(jLabel1))
                .addGap(0, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtMasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(btnReset))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(btnSave)
                                    .addComponent(cbLoaisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(btnUpdate)
                            .addComponent(cbHangsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGianhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFind)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtGiaxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbDonvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addComponent(jButton6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(503, 503, 503)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        List<SanPham> spList=SanPhamModify.findAll();
        selectedIndex=tblSanpham.getSelectedRow();
       
        if(selectedIndex>=0){
            SanPham sp=spList.get(selectedIndex);
            
            int option=JOptionPane.showConfirmDialog(this, "BẠN CÓ MUỐN XÓA SẢN PHẨM NÀY ?");
          
            
            if(option==0){
              SanPhamModify.delete(sp.getMaSP());
              JOptionPane.showMessageDialog(rootPane, "XÓA THÀNH CÔNG !");
              showSanPham();
              showInfo();
            }
        }else{
            SanPham sp=SanPhamModify.findByID(txtMasp.getText());
            int option=JOptionPane.showConfirmDialog(this, "BẠN CÓ MUỐN XÓA SẢN PHẨM NÀY ?");
         
            SanPhamModify.delete(sp.getMaSP());
            JOptionPane.showMessageDialog(rootPane, "XÓA THÀNH CÔNG!");
            showSanPham();
            showInfo();
            }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblSanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanphamMouseClicked
        // TODO add your handling code here:
        showSelectedRow();
    }//GEN-LAST:event_tblSanphamMouseClicked

    private void cbLoaispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoaispActionPerformed

        tenloaisp=(String) cbLoaisp.getSelectedItem();
        
    }//GEN-LAST:event_cbLoaispActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String Masp=txtMasp.getText();
        String Tensp=txtTensp.getText();
        int giaNhap=0;
        int giaXuat=0;
        int soLuong=0;
        String donVi=(String) cbDonvi.getSelectedItem();
        LoaiSanPham lsp=LoaiSPModify.findByExName(tenloaisp);
        NhaCC ncc=NhaCCModify.findByExName(tenNhasx);
        boolean isOK=true;
        
        if(SanPhamModify.compareByID(Masp)){
            JOptionPane.showMessageDialog(rootPane, "MÃ LOẠI SẢN PHẨM ĐÃ TỒN TẠI!");
            isOK=false;
            
        }
        try{
            soLuong=Integer.parseInt(txtSoluong.getText());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "SỐ LƯỢNG PHẢI LÀ SỐ LỚN HƠN 0 VÀ KHÔNG ĐƯỢC ĐỂ TRỐNG !");
            isOK=false;
        }
        if(soLuong<0){
            JOptionPane.showMessageDialog(rootPane, "SỐ LƯỢNG PHẢI LÀ SỐ LỚN HƠN 0 VÀ KHÔNG ĐƯỢC ĐỂ TRỐNG !");
            isOK=false;
        }
        
        try{
            giaNhap=Integer.parseInt(txtGianhap.getText());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "GIÁ NHẬP PHẢI LÀ SỐ LỚN HƠN 1000 VÀ KHÔNG ĐƯỢC ĐỂ TRỐNG !");
            isOK=false;
        }
        if(giaNhap/1000<1){
            JOptionPane.showMessageDialog(rootPane, "GIÁ NHẬP PHẢI LÀ SỐ LỚN HƠN 1000 VÀ KHÔNG ĐƯỢC ĐỂ TRỐNG!");
            isOK=false;
        }
        try{
            giaXuat=Integer.parseInt(txtGiaxuat.getText());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "GIÁ XUẤT PHẢI LÀ SỐ LỚN HƠN 1000 VÀ KHÔNG ĐƯỢC ĐỂ TRỐNG!");
            isOK=false;
        }
        if(giaXuat/1000<1){
            JOptionPane.showMessageDialog(rootPane, "GIÁ NHẬP PHẢI LÀ SỐ LỚN HƠN 1000 VÀ KHÔNG ĐƯỢC ĐỂ TRỐNG!");
            isOK=false;
        }
        if(isOK){

          SanPham sp=new SanPham(Masp,Tensp,giaNhap,giaXuat,soLuong,donVi,lsp.getMaLoaiSP(),ncc.getMaNCC());
          SanPhamModify.insert(sp);
      
            JOptionPane.showMessageDialog(rootPane, "LƯU THÀNH CÔNG!");
        }
 
          showSanPham();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cbHangsxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHangsxActionPerformed
        // TODO add your handling code here:
        tenNhasx=(String) cbHangsx.getSelectedItem();
    }//GEN-LAST:event_cbHangsxActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        TaoCode code=new TaoCode();
        int id=code.createSpID();
         txtMasp.setText("LDTK"+id);
         txtTensp.setText("");
         txtGianhap.setText("");
         txtGiaxuat.setText("");
         txtSoluong.setText("");
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtGiaxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaxuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaxuatActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String Masp=txtMasp.getText();
        String Tensp=txtTensp.getText();
        int giaNhap=0;
        int giaXuat=0;
        int soLuong=0;
        String donVi=(String) cbDonvi.getSelectedItem();
        LoaiSanPham lsp=LoaiSPModify.findByExName(tenloaisp);
        NhaCC ncc=NhaCCModify.findByExName(tenNhasx);
        boolean isOK=true;
        
//        if(SanPhamModify.compareByID(Masp)){
//            JOptionPane.showMessageDialog(rootPane, "MA LOAI SAN PHAM DA TON TAI !");
//            isOK=false;
//            
//        }
        try{
            soLuong=Integer.parseInt(txtSoluong.getText());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "SỐ LƯỢNG PHẢI LÀ SỐ LỚN HƠN 0 VÀ KHÔNG ĐƯỢC ĐỂ TRỐNG !");
            isOK=false;
        }
        if(soLuong<0){
            JOptionPane.showMessageDialog(rootPane, "SỐ LƯỢNG PHẢI LÀ SỐ LỚN HƠN 0 VÀ KHÔNG ĐƯỢC ĐỂ TRỐNG !");
            isOK=false;
        }
        
        try{
            giaNhap=Integer.parseInt(txtGianhap.getText());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "GIÁ NHẬP PHẢI LÀ SỐ LỚN HƠN 1000 VÀ KHÔNG ĐƯỢC ĐỂ TRỐNG !");
            isOK=false;
        }
        if(giaNhap/1000<1){
            JOptionPane.showMessageDialog(rootPane, "GIÁ NHẬP PHẢI LÀ SỐ LỚN HƠN 1000 VÀ KHÔNG ĐƯỢC ĐỂ TRỐNG !");
            isOK=false;
        }
        try{
            giaXuat=Integer.parseInt(txtGiaxuat.getText());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "GIÁ XUẤT PHẢI LÀ SỐ LỚN HƠN 1000 VÀ KHÔNG ĐƯỢC ĐỂ TRỐNG !");
            isOK=false;
        }
        if(giaXuat/1000<1){
            JOptionPane.showMessageDialog(rootPane, "GIÁ XUẤT PHẢI LÀ SỐ LỚN HƠN 1000 VÀ KHÔNG ĐƯỢC ĐỂ TRỐNG!");
            isOK=false;
        }
        if(isOK){

          SanPham sp=new SanPham(Masp,Tensp,giaNhap,giaXuat,soLuong,donVi,lsp.getMaLoaiSP(),ncc.getMaNCC());
          SanPhamModify.update(sp);
            JOptionPane.showMessageDialog(rootPane, "CẬP NHẬT THÀNH CÔNG !");
        }
 
        showSanPham();
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
         String input =JOptionPane.showInputDialog(this,"NHẬP TÊN SẢN PHẨM CẦN TÌM KIẾM:");
        if(input!=null&&input.length()>0){
            List<SanPham> spList=SanPhamModify.findByName(input);
            
            tableModel.setRowCount(0);
            spList.forEach(sp -> {
            tableModel.addRow(new Object[] {sp.getMaSP(),
                sp.getTenSP(),
                LoaiSPModify.findByID(sp.getMaLoaiSP()).getTenLoaiSP(),
                NhaCCModify.findByID(sp.getMaNCC()).getTenNCC(),
                sp.getGiaNhap(),sp.getGiaXuat(),
                sp.getDonVi(),sp.getSoLuong()
            });
           
        });
        }else{
            showSanPham();
    }                   
    }//GEN-LAST:event_btnFindActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MENUFORM(txtChucvu.getText()).setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed
    private void showComboLoaiSP(){
        List<LoaiSanPham> loaiSP=LoaiSPModify.findAll();
       
        for(LoaiSanPham sp:loaiSP){
            cbLoaisp.addItem(sp.getTenLoaiSP());
        }
    }
    private void showComboNcc(){
        List<NhaCC> nccList=NhaCCModify.findAll();
        
        for(NhaCC ncc:nccList){
            cbHangsx.addItem(ncc.getTenNCC());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SANPHAMFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SANPHAMFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SANPHAMFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SANPHAMFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SANPHAMFORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbDonvi;
    private javax.swing.JComboBox<String> cbHangsx;
    private javax.swing.JComboBox<String> cbLoaisp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSanpham;
    private javax.swing.JLabel txtChucvu;
    private javax.swing.JTextField txtGianhap;
    private javax.swing.JTextField txtGiaxuat;
    private javax.swing.JTextField txtMasp;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTensp;
    // End of variables declaration//GEN-END:variables
}
